name: Cyre Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., patch, minor, major, or specific version)'
        required: true
        default: 'patch'

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Setup PNPM with explicit version
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      # Setup Node.js with correct caching
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      
      # Now run the install with proper error handling
      - name: Install dependencies
        run: |
          # Make sure pnpm-lock.yaml exists
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "Creating pnpm-lock.yaml"
            pnpm install --lockfile-only
          fi
          
          pnpm install
      
      # Set NODE_OPTIONS for node.js crypto (in case tests use it)
      - name: Set Node Options
        run: |
          echo "NODE_OPTIONS=--experimental-global-webcrypto" >> $GITHUB_ENV
      
      - name: Run tests
        run: pnpm test
      
      - name: Build package
        run: pnpm build
      
      - name: Version bump (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [[ "${{ github.event.inputs.version }}" =~ ^(patch|minor|major)$ ]]; then
            pnpm version ${{ github.event.inputs.version }} -m "Bump version to %s [skip ci]"
          else
            pnpm version ${{ github.event.inputs.version }} -m "Set version to %s [skip ci]"
          fi
          
      - name: Push version changes
        if: github.event_name == 'workflow_dispatch'
        run: git push --follow-tags
      
      - name: Publish to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}